---
namespace: imp1sh
name: ansible_managemynetwork
version: 0.5.2
readme: README.md
authors:
  - Jochen Demmer <jochen@libcom.de>
description: A collection of several roles that I need to manage my network. You can use it as well.
license_file: 'LICENSE'
tags: [server, system, management, freebsd, debian, network, services, openwrt]
dependencies: {}
repository: https://github.com/imp1sh/ansible_managemynetwork
documentation: https://github.com/imp1sh/ansible_managemynetwork/blob/main/README.md
homepage: https://wiki.junicast.de
issues: https://github.com/imp1sh/ansible_managemynetwork/issues
