---
# tasks file for ansible_podman
- name: MMN Podman - Prepare and install packagessystemd tasks
  ansible.builtin.include_tasks:
    file: 0install.yml

- name: MMN Podman - Network
  ansible.builtin.include_tasks:
    file: 1prepare.yml

- name: MMN Podman - Create containers
  containers.podman.podman_containers:
    containers: "{{ podman_containers }}"
  when: podman_containers is defined

- name: MMN Podman - Post tasks
  ansible.builtin.include_tasks:
    file: 4post.yml
  when: podman_containers is defined
