---
# VARS
- name: "MMN cacert - Setting OS variables"
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - "vars"

- name: "MMN cacert - Set packages to install"
  ansible.builtin.set_fact:
    packages_installrole: "{{ cacert_packages }}"
  when: ansible_distribution == 'OpenWrt'

# PACKAGES
- name: "MMN cacert - Run package role"
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_packages
  when: ansible_distribution == 'OpenWrt'

# CERTS   
- name: "MMN cacert - Manage CA key and cert"
  ansible.builtin.include_tasks: ca_instance.yml
  loop: "{{ cacert_cas | dict2items }}"
  loop_control:
    loop_var: "cacert_ca"

      #- name: "MMN cacert - Manage server certs"
      #  ansible.builtin.include_tasks: servercert.yml
      #  loop: "{{ cacert_cas | dict2items }}"
      #  loop_control:
      #    loop_var: "cacert_ca"
