---
- name: Block task if user shall be created on this very host
  block:
    - name: The user will be installed
      ansible.builtin.debug:
        var: user.key
    - name: Set fact for package install
      ansible.builtin.set_fact:
        packages_installrole: "{{ shellpackages[user.value.shell] }}"
      when:
        - user.value.shell is defined
    - name: Install package for shell
      ansible.builtin.include_role:
        name: imp1sh.ansible_managemynetwork.ansible_openwrtpackages
      when:
        user.value.shell is defined
    - name: set users shell for this OS
      set_fact:
        usershell: "{{ shells[user.value.shell] }}"
      when: user.value.shell is defined
    - name: debug
      debug:
        msg: "{{ system_users_setpassword_deploypath }}/{{ 99 + index }}{{ system_users_setpassword_deployfile }}-{{ user.key }}"
    - name: Make sure init script deploypath exists
      ansible.builtin.file:
        path: "{{ system_users_setpassword_deploypath }}"
        state: directory
    - name: deploy init script for user
      ansible.builtin.template:
        src: imagebuilderuser.j2
        dest: "{{ system_users_setpassword_deploypath }}/{{ index }}{{ system_users_setpassword_deployfile }}-{{ user.key }}"
  when: user.key in list_of_users
