---
- name: Block task if user shall be created on this very host
  block:
    - name: The user will be installed
      ansible.builtin.debug:
        var: user.key
    - name: Set fact for package install
      ansible.builtin.set_fact:
        packages_installrole: "{{ shellpackages[user.value.shell] }}"
      when:
        - user.value.shell is defined
    - name: Install package for shell
      ansible.builtin.include_role:
        name: imp1sh.ansible_managemynetwork.ansible_packages
      when:
        user.value.shell is defined
    - name: Create user
      ansible.builtin.include_tasks: 04justdoit.yml
    - name: Deploy files (optional)
      ansible.builtin.include_tasks: "05deployfiles.yml"
      loop: "{{ user.value.deployfiles }}"
      loop_control:
        loop_var: fileitem
      when:
        - user.value.deployfiles is defined
  when: user.key in list_of_users
