---
- name: "MMN borgmatic - Make sure ssh keys are present"
  community.crypto.openssh_keypair:
    type: "ed25519"
    path: "{{ borgmatic_sshdir }}id_ed25519"
  register: sshkey
- name: "MMN borgmatic - Iterate over target repositories"
  ansible.builtin.include_tasks: "5ssh_container_repositories.yml"
  loop: "{{ borgmatic_repositories | dict2items }}"
  loop_control:
    loop_var: "targetrepo"
