---
# tasks file for ansible_borgmatic
- name: MMN borgmatic - include OS vars
  include_vars: "{{ ansible_distribution }}.yml"
- name: MMN borgmatic - Setting absent state for intallation of distribution packages
  ansible.builtin.set_fact:
    borgmatic_package_state: absent
  when: borgmatic_via_pip
- name: MMN borgmatic - Setting present state for installation of distribution packages
  ansible.builtin.set_fact:
    borgmatic_package_state: present
  when: not borgmatic_via_pip
- name: MMN borgmatic - include install tasks
  include_tasks: 1install.yml
- name: MMN borgmatic - Include cron tasks
  include_tasks: 3cron.yml
- name: MMN borgmatic - Include systemd timer task
  include_tasks: 4systemd_timer.yml
  when: borgmatic_systemd_manage
- name: MMN borgmatic - Include ssh tasks
  include_tasks: 5ssh.yml
  loop: "{{ borgmatic_repositories | dict2items }}"
  loop_control:
    loop_var: borgmatic_repository
  when: borgmatic_ssh_manage
- name: MMN borgmatic - Provide borgmatic config
  ansible.builtin.template:
    src: config.yaml.jinja2
    dest: "{{ borgmatic_pathconfig }}/{{ borgmatic_fileconfig }}"
    owner: "{{ borgmatic_fileconfig_owner }}"
    group: "{{ borgmatic_fileconfig_group }}"
    mode: 0740
- name: MMN borgmatic - Init repository
  ansible.builtin.command: "{{ borgmatic_venv_wrapper }} -c {{ borgmatic_pathconfig }}/{{ borgmatic_fileconfig }} init --encryption repokey"
  register: borgmatic_init_success
