- name: assemble repository string
  include_tasks: xassemblerepo.yml
- name: deploy restic configuration
  ansible.builtin.template:
    src: restic.conf.jinja2
    dest: "{{ restic_deploypath }}/{{ restic_deployfile }}_{{ backupitem['name'] }}"
    mode: 0600
- name: deploy restic password file
  ansible.builtin.template:
    src: password.jinja2
    dest: "{{ restic_deploypath_passwordfile }}/{{ restic_deployfile_passwordfile }}_{{ backupitem['name'] }}"
    mode: 0600
