---
# tasks file for ansible_talos
- name: MMN Talos - Install talosctl
  include_tasks: 01_talosctl_install.yml

- name: MMN Talos - Configure Cluster
  include_tasks: 02_cluster_configure.yml

- name: MMN Talos - Apply Config
  include_tasks: 03_config_apply.yml

- name: MMN Talos - Export Talosctl Config
  include_tasks: 04_config_export.yml

- name: MMN Talos - Add Workers
  include_tasks: 05_workers_add.yml
